# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
- psql -c 'create database test;' -U postgres

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2
# - r: 3.1  # fails with S4 weirdness
